name: build and publish docker image

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8

        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build
        run: chmod +x ./gradlew && ./gradlew clean build

      - run: mv build/libs/*.jar build/libs/app.jar

      - uses: actions/upload-artifact@v1
        with:
          name: app
          path: build/libs/

  deploy:
    name: Deploy
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: app
          path: build/libs/

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Build and push
        run: |
          docker buildx build \
          --platform linux/amd64,linux/arm/v7,linux/arm64 \
          --push=true \
          --output type=registry \
          --tag slaaavyn/home-backend \
          --file ./Dockerfile .